#!/bin/bash

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
NC='\033[0m' # No Color

echo
echo -e "${YELLOW}Running code style checks...${NC}"
echo

# Get staged files
FILES=$(git diff --cached --name-only --diff-filter=ACM)

# Check if there are staged files
if [ -z "$FILES" ]
then
    echo -e "${GREEN}No staged files, skipping pre-commit hook...${NC}"
    echo
    exit 0
fi

# Run Laravel Pint on staged files
./vendor/bin/pint --test $FILES > /dev/null
PINT_EXIT_CODE=$?

# Check for Pint errors
if [ $PINT_EXIT_CODE -eq 0 ]
then
    echo -e "${GREEN}Your code looks good, proceeding with the commit...${NC}"
    echo
    exit 0
else
    echo -e "${RED}Your code does not meet code style requirements. Please run \`make pint\`, stage style fixes and try again.${NC}"
    echo
    exit 1
fi
