version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "7827:8000" # <--- Caso queira usar uma porta diferente, altere o número da esquerda.
    # restart: always
    env_file:
      - .env.docker
    depends_on:
      pgsql:
        condition: service_healthy

  pgsql:
    image: postgres:14
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: laravel-blog-api
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"
        ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db_data:
    driver: local
