name: CI

on:
  pull_request:
    branches: [ master ]

jobs:
  Test:
    runs-on: ubuntu-22.04
    container:
      image: kirschbaumdevelopment/laravel-test-runner:8.1
    services:
      pgsql:
        image: postgres:14
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: testing
        options: --health-cmd "pg_isready -d testing -U postgres" --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - uses: actions/checkout@v3

      - name: Set ENV
        run: mv .env.docker .env

      - name: Install Dependencies
        run: |
          apt update
          apt install -y php8.1-xdebug
          composer install -q --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist

      - name: Style Check
        run: vendor/bin/pint --test


      - name: Run Tests
        run: XDEBUG_MODE=coverage php artisan test --coverage --min=80