name: CI

on:
  pull_request:
    branches: [ master ]

jobs:
  Test:
    runs-on: ubuntu-22.04
    container:
      image: ubuntu:22.04
    services:
      pgsql:
        image: postgres:14
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: testing
        options: --health-cmd "pg_isready -d testing -U postgres" --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - uses: actions/checkout@v3

      - name: Setup PHP with Xdebug
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          coverage: xdebug

      - name: Set ENV
        run: mv .env.docker .env

      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist

      - name: Style Check
        run: vendor/bin/pint --test

      - name: Run Tests
        run: XDEBUG_MODE=coverage php artisan test --coverage --min=80